<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>vm2.Glob.Api</RootNamespace>

        <!-- NuGet Package Metadata -->
        <PackageId>vm2.Glob.Api</PackageId>
        <Title>Cross-platform Glob Pattern Matching API</Title>
        <Description>
        A fast, cross-platform glob pattern matching API for finding files and directories. Implements POSIX.2 glob specification.
        </Description>
        <PackageTags>glob pattern matching api cross-platform file-search directory-search</PackageTags>
        <PackageProjectUrl>https://github.com/vmelamed/vm2.Glob/blob/main/src/Glob.Api/Glob.Api.csproj</PackageProjectUrl>
        <RepositoryUrl>https://github.com/vmelamed/vm2.Glob</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageReleaseNotes>Initial release.</PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Glob.Api.Tests" />
        <InternalsVisibleTo Include="Glob.Api.FakeFileSystem.Tests" />
        <InternalsVisibleTo Include="Glob.Api.FakeFileSystem" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="../../README.md" Pack="true" PackagePath="\" />
        <None Include="../../LICENSE" Pack="true" PackagePath="\" />
        <None Include="../../CHANGELOG.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
