<Project>
    <PropertyGroup>
        <RootNamespace>vm2.Glob.Examples</RootNamespace>
        <IsPackable>false</IsPackable>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="System.CommandLine" />
    </ItemGroup>
</Project>
