<Project>
    <!-- ================ Common Settings for All projects ================ -->
    <PropertyGroup Label="Packages">
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RootNamespace>vm2.Glob</RootNamespace>
        <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
        <IsTrimmable>true</IsTrimmable>
        <TieredPGO>true</TieredPGO>
    </PropertyGroup>

    <!-- ================ Package properties for all vm2 packages ================ -->
    <PropertyGroup Label="NuGetGlobal">
        <IsPackable>true</IsPackable>
        <IncludeSymbols>true</IncludeSymbols>
        <Company>vm</Company>
        <Product>vm2</Product>
        <ProductName>vm2 packages and tools</ProductName>
        <Authors>Val Melamed</Authors>
        <Copyright>Copyright ©2025-2026 vm</Copyright>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <IncludeSymbols>True</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <EnablePackageValidation>true</EnablePackageValidation>
        <EmbedAllSources>true</EmbedAllSources>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <RepositoryType>git</RepositoryType>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <RepositoryUrl>https://github.com/vmelamed/vm2.Glob</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="all" />
        <!-- <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" /> -->
    </ItemGroup>
</Project>
