<Project>
    <PropertyGroup Label="Packages">
        <RootNamespace>vm2.Glob.Api.Benchmarks</RootNamespace>
        <OutputType>Exe</OutputType>
        <IsPackable>False</IsPackable>
        <IncludeSymbols>False</IncludeSymbols>
        <GenerateDocumentationFile>False</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);CA1701;CA1702;CA1707;CA1806;CA2211;CS0618;CS1572;CS1573;CS1574;CS1591;CS1711;IDE0021;IDE0022;IDE0039;IDE0065;IDE1006;IDE2000;IDE2002;IDE0058;IDE0290</NoWarn>
        <!-- To show up in the VS test explorer, see also below in the package references:
        <RestorePackagesWithLockFile Condition="$(BuildingInsideVisualStudio) == 'true')">false</RestorePackagesWithLockFile>
        -->
        <TieredPGO>false</TieredPGO>        <!-- benchmarks often prefer consistent JIT settings -->
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" />
        <PackageReference Include="BenchmarkDotNet.Annotations" />
        <!-- To show up in the VS test explorer (with some perf. penalties!)
        <PackageReference Include="BenchmarkDotNet.TestAdapter" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        -->
        <!-- for running with Visual Studio profiler:
        <PackageReference Include="Microsoft.VisualStudio.DiagnosticsHub.BenchmarkDotNetDiagnosers" />
        -->
    </ItemGroup>

    <ItemGroup>
        <Using Include="BenchmarkDotNet" />
        <Using Include="BenchmarkDotNet.Attributes" />
        <Using Include="BenchmarkDotNet.Configs" />
        <Using Include="BenchmarkDotNet.Jobs" />
        <Using Include="BenchmarkDotNet.Order" />
        <Using Include="BenchmarkDotNet.Running" />
    </ItemGroup>

</Project>
